---
title: "ESM 232 Assignment 8"
author: "Madeline Oliver, Jennifer Truong, Alex Milward"
date: "5/19/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(purrr)
library(lubridate)
```

# Develop your performance metric

Our metric is BIAS or Percent Error (Err). We'll be calculating average percent error for the whole dataset.

```{r}
# Code metric as a function
source("err.r")

# read in data
sager = read.table("sager.txt", header=T)
head(sager)

msage = read.table("sagerm.txt", header=T)

```

```{r}
# clean multiple model results streamflow data in sagerm.txt

# add date from the existing columns of day, month, year
sager = sager %>%
  mutate(date=make_date(year=year, 
                        month=month,
                        day=day))

# each column in msage is streamflow for a different parameter set

# lets say we know the start date from our earlier output
msage$date = sager$date
head(msage)
msage$month = sager$month
msage$year = sager$year
msage$day = sager$day
msage$wy = sager$wy

# and we still have observed data from above
# useful to combine by date to make sure that streamflow and observe match

msage$obs = sager$obs

# how can we plot all results
# to turn all the columns of different outputs into a single column identified by "run"
msagel = msage %>% gather(key="run",value="streamflow", -date, -month, -day, -year, -wy, -obs)

# compute performance measures for all output
res = msage %>% 
  select(-date, -month, -day, -year, -wy, -obs) %>% 
  map_dbl(~err(m=.x, o=msage$obs))

summary(res)

```

```{r}
# if we want to keep track of which statistics is associated with each run, we need a unique identifies
# a ID that tracks each model output - lets use the column names
simnames = names(msage %>% select(-date, -month, -day,-year,-wy, -obs))
results = cbind.data.frame(simnames=simnames, err=res)
# another example using our low flow statistics
# use apply to compute for all the data
res = msage %>% select(-date, -month, -day, -year, -wy, -obs ) %>% map_dbl(~check_minannual( o=msage$obs, 
                                                                                             month=msage$month, 
                                                                                             day=msage$day, 
                                                                                             year=msage$year, wy=msage$wy, 
                                                                                             m=.x))
# add to our results
results$minannual_cor = res
```

Find the simulation that gives the best performance (record that and add to the quiz on gauchospace)
```{r}
# interesting to look at range of metrics - could use this to decide on acceptable values
summary(results)

```
Simulation ??  has the min number for Err.

Create boxplot of metric applied to sagerm.txt
```{r}
# graph err values
ggplot(results, aes(err)) +
  geom_boxplot() +
  labs(x = "Err") +
  theme_minimal()

```
```



